import requirementFormModel from './requirementFormModel'

const {
    formFields : {
        buyerName,
        buyerAddress,
        buyerBirthDate,
        buyerContactNo,
        buyerCitizenship,
        buyerEmailAddress,
        buyerFacebook,
        buyerGender,
        buyerCivilStatus,
        buyerTitlingInstruction,
        buyerTitlingInstructionOther,
        buyerFinancing,
        buyerNegativeDataBankRecordsCancelledCreditCards,
        buyerNegativeDataBankRecordsBouncedChecks,
        buyerNegativeDataBankRecordsPendingCourtCases,
        buyerNegativeDataBankRecordsUnpaidTelecomBill,
        buyerNegativeDataBankRecordsOthers,
        buyerPagIbigMembership,
        buyerPagIbigMembershipNumberOfYears,
        buyerPagIbigMembershipUpdated,
        buyerPagIbigMembershipWOHML,
        buyerPagIbigMembershipWFHL,
        buyerEmployerDetailsCompanyName,
        buyerEmployerDetailsAddress,
        buyerEmployerDetailsContactNo,
        buyerEmployerDetailsEmailAdress,
        buyerEmployerDetailsImmediateSuperior,
        documentValidIds,
        documentSpouseValidIds,
        documentTINNumber,
        documentBirthCertificate,
        documentMarriageCertificate,
        documentClearOneByOnePicture,
        documentProofOfMailingOrBilling,
        documentPostDatedChecks,
        documentAAR,
        documentSPA,
        documentBankAndPagIbigSPA,
        documentOAAC,
        documentOthers,
        documentLocallyEmployedNCEC,
        documentLocallyEmployedLatestITR,
        documentLocallyEmployed3MonthsOfPayslips,
        documentSelfEmployedFormalAFS,
        documentSelfEmployedFormalLatest6monsBankStatements,
        documentSelfEmployedFormalLatestITR,
        documentSelfEmployedInformalCOEwithIdSignatory,
        documentSelfEmployedInformalCOEwithOtherAttachment,
        documentOFWCountry,
        documentOFWNCEC,
        documentOFW3MonsPayslipsOrRemittance,
        documentOFWBankStatements,
        documentOFWPassportWithEntryExit,
        computationSellingPrice,
        computationDiscount,
        computationNetSellingPrice,
        computationTaxesAndFees,
        computationTotalReceivable,
        computationNumberOfDownpayments,
        computationEstimatedMonthlyAmortization,
        computationGrossIncome,
        computationMonthlyIncomeRatio,
        computationRemarks,
        screeningInterviewedBy,
        screeningConforme,
        briefingReservationDate,
        briefingSalesChannel,
        briefingProjectName,
        briefingPH,
        briefingLot,
        briefingBlock,
        briefingBroker,
        briefingDirectSeller,
        briefingFinancing,
        briefingReservationDocuments,
        briefingReferenceNumber,
        briefingConforme,
        briefingBriefedBy,
        briefingWitness,
    }
} = requirementFormModel;

export default {
    [buyerName.name] : '',
        [buyerAddress.name] : '',
        [buyerBirthDate.name] : '',
        [buyerContactNo.name] : '',
        [buyerCitizenship.name] : '',
        [buyerEmailAddress.name] : '',
        [buyerFacebook.name] : '',
        [buyerGender.name] : '',
        [buyerCivilStatus.name] : '',
        [buyerTitlingInstruction.name] : '',
        [buyerTitlingInstructionOther.name] : 'none',
        [buyerFinancing.name] : '',
        [buyerNegativeDataBankRecordsCancelledCreditCards.name] : false,
        [buyerNegativeDataBankRecordsBouncedChecks.name] : false,
        [buyerNegativeDataBankRecordsPendingCourtCases.name] : false,
        [buyerNegativeDataBankRecordsUnpaidTelecomBill.name] : false,
        [buyerNegativeDataBankRecordsOthers.name] : '',
        [buyerPagIbigMembership.name] : '',
        [buyerPagIbigMembershipNumberOfYears.name] : '',
        [buyerPagIbigMembershipUpdated.name] : '',
        [buyerPagIbigMembershipWOHML.name] : '',
        [buyerPagIbigMembershipWFHL.name] : '',
        [buyerEmployerDetailsCompanyName.name] : '',
        [buyerEmployerDetailsAddress.name] : '',
        [buyerEmployerDetailsContactNo.name] : '',
        [buyerEmployerDetailsEmailAdress.name] : '',
        [buyerEmployerDetailsImmediateSuperior.name] : '',
        [documentValidIds.name] : '',
        [documentSpouseValidIds.name] : '',
        [documentTINNumber.name] : '',
        [documentBirthCertificate.name] : '',
        [documentMarriageCertificate.name] : '',
        [documentClearOneByOnePicture.name] : '',
        [documentProofOfMailingOrBilling.name] : '',
        [documentPostDatedChecks.name] : '',
        [documentAAR.name] : '',
        [documentSPA.name] : '',
        [documentBankAndPagIbigSPA.name] : '',
        [documentOAAC.name] : '',
        [documentOthers.name] : '',
        [documentLocallyEmployedNCEC.name] : '',
        [documentLocallyEmployedLatestITR.name] : '',
        [documentLocallyEmployed3MonthsOfPayslips.name] : '',
        [documentSelfEmployedFormalAFS.name] : '',
        [documentSelfEmployedFormalLatest6monsBankStatements.name] : '',
        [documentSelfEmployedFormalLatestITR.name] : '',
        [documentSelfEmployedInformalCOEwithIdSignatory.name] : '',
        [documentSelfEmployedInformalCOEwithOtherAttachment.name] : '',
        [documentOFWCountry.name] : '',
        [documentOFWNCEC.name] : '',
        [documentOFW3MonsPayslipsOrRemittance.name] : '',
        [documentOFWBankStatements.name] : '',
        [documentOFWPassportWithEntryExit.name] : '',
        [computationSellingPrice.name] : '',
        [computationDiscount.name] : 0,
        [computationNetSellingPrice.name] : '',
        [computationTaxesAndFees.name] : '',
        [computationTaxesAndFees.name] : '',
        [computationTotalReceivable.name] : '',
        [computationNumberOfDownpayments.name] : '',
        [computationEstimatedMonthlyAmortization.name] : '',
        [computationGrossIncome.name] : '',
        [computationMonthlyIncomeRatio.name] : '',
        [computationRemarks.name] : '',
        [screeningInterviewedBy.name] : '',
        [screeningConforme.name] : '',
        [briefingReservationDate.name] : '',
        [briefingSalesChannel.name] : '',
        [briefingProjectName.name] : '',
        [briefingPH.name] : '',
        [briefingLot.name] : '',
        [briefingBlock.name] : '',
        [briefingBroker.name] : '',
        [briefingDirectSeller.name] : '',
        [briefingFinancing.name] : '',
        [briefingReservationDocuments.name] : '',
        [briefingReferenceNumber.name] : '',
        [briefingConforme.name] : '',
        [briefingBriefedBy.name] : '',
        [briefingWitness.name] : ''
}